//
//  LoginViewController.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/2.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {

	var presenter: LoginPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
