//
//  MainViewController.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/5.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainViewController: UITabBarController, MainViewProtocol {

	var presenter: MainPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
