//
//  ReservationProtocols.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ReservationWireframeProtocol: class {

}
//MARK: Presenter -
protocol ReservationPresenterProtocol: class {

    var interactor: ReservationInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ReservationInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ReservationInteractorInputProtocol: class {

    var presenter: ReservationInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ReservationViewProtocol: class {

    var presenter: ReservationPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
