//
//  ReservationViewController.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ReservationViewController: UIViewController, ReservationViewProtocol {

	var presenter: ReservationPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
