//
//  ConversationListInteractor.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/7.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConversationListInteractor: ConversationListInteractorInputProtocol {


    weak var presenter: ConversationListPresenterProtocol?
    
    func conversationList() -> [Any] {
        return [1, 2, 3, 4, 5, 6]
    }
    
}
