//
//  ConversationListPresenter.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/7.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConversationListPresenter: ConversationListPresenterProtocol {

    weak private var view: ConversationListViewProtocol?
    var interactor: ConversationListInteractorInputProtocol?
    private let router: ConversationListWireframeProtocol

    init(interface: ConversationListViewProtocol, interactor: ConversationListInteractorInputProtocol?, router: ConversationListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

// MARK: ConversationListPresenterProtocol

extension ConversationListPresenter {
    
    func tableViewSections() -> [SectionModel<RowModel>] {
        // 获取源对话数据
        let list  = self.interactor?.conversationList()
        // 转换为RowModel类型
        let rows = list?.map {
            return RowModel.init(rowValue: $0 , reuseIdentifier: "ConversationListCell")
        }
        
        let section = SectionModel.init(sectionItems: rows ?? [])

        return [section]
    }
}
