//
//  ConversationListProtocols.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/7.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ConversationListWireframeProtocol: class {

}

//MARK: Presenter -
protocol ConversationListPresenterProtocol: class {
    var interactor: ConversationListInteractorInputProtocol? { get set }

    func tableViewSections() ->[SectionModel<RowModel>]
}

//MARK: Interactor -
protocol ConversationListInteractorOutputProtocol: class {
    
    /* Interactor -> Presenter */
}

protocol ConversationListInteractorInputProtocol: class {
    
    var presenter: ConversationListPresenterProtocol?  { get set }
    
    /* Presenter -> Interactor */
    func conversationList() ->[Any]
}

//MARK: View -
protocol ConversationListViewProtocol: class {

  var presenter: ConversationListPresenterProtocol?  { get set }
}
