//
//  IndexViewController.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IndexViewController: UIViewController, IndexViewProtocol {

	var presenter: IndexPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
