//
//  IndexRouter.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IndexRouter: IndexWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
    
        let stroyb = UIStoryboard.init(name: "Main", bundle: nil)
        let view = stroyb.instantiateViewController(withIdentifier: "IndexViewController") as! IndexViewController
        
        let interactor = IndexInteractor()
        let router = IndexRouter()
        let presenter = IndexPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
