//
//  IndexPresenter.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IndexPresenter: IndexPresenterProtocol, IndexInteractorOutputProtocol {

    weak private var view: IndexViewProtocol?
    var interactor: IndexInteractorInputProtocol?
    private let router: IndexWireframeProtocol

    init(interface: IndexViewProtocol, interactor: IndexInteractorInputProtocol?, router: IndexWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
