//
//  SettiingProtocols.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SettiingWireframeProtocol: class {

}
//MARK: Presenter -
protocol SettiingPresenterProtocol: class {

    var interactor: SettiingInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SettiingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SettiingInteractorInputProtocol: class {

    var presenter: SettiingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SettiingViewProtocol: class {

    var presenter: SettiingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
