//
//  SettiingViewController.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SettiingViewController: UIViewController, SettiingViewProtocol {

	var presenter: SettiingPresenterProtocol?

  @IBOutlet weak var tableView: UITableView!
  @IBOutlet weak var signOutButton: UIButton!
    
	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
