//
//  SettiingRouter.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/8.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SettiingRouter: SettiingWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let stroyb = UIStoryboard.init(name: "Settings", bundle: nil)
        let view = stroyb.instantiateViewController(withIdentifier: "SettiingViewController") as! SettiingViewController

        let interactor = SettiingInteractor()
        let router = SettiingRouter()
        let presenter = SettiingPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
