//
//  MeProtocols.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/7.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MeWireframeProtocol: class {
    func pushToSettingViewController()
}

//MARK: Presenter -
protocol MePresenterProtocol: class {

    var interactor: MeInteractorInputProtocol? { get set }
    
    // action
    func handlerSettingAction()
}

//MARK: Interactor -
protocol MeInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MeInteractorInputProtocol: class {

    var presenter: MeInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MeViewProtocol: class {

    var presenter: MePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
