//
//  MePresenter.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/7.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MePresenter: MePresenterProtocol, MeInteractorOutputProtocol {

    weak private var view: MeViewProtocol?
    var interactor: MeInteractorInputProtocol?
    private let router: MeWireframeProtocol

    init(interface: MeViewProtocol, interactor: MeInteractorInputProtocol?, router: MeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
