//
//  MeViewController.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/7.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MeViewController: UIViewController, MeViewProtocol {

	var presenter: MePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
