//
//  MainProtocols.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/5.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainWireframeProtocol: class {

}
//MARK: Presenter -
protocol MainPresenterProtocol: class {

    var interactor: MainInteractorInputProtocol? { get set }
    
    func didSelectTabBarItem(at Index: Int)
}

//MARK: Interactor -
protocol MainInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MainInteractorInputProtocol: class {

    var presenter: MainInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MainViewProtocol: class {

    var presenter: MainPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
