//
//  MainRouter.swift
//  BodyBuild
//
//  Created 陈琪 on 2018/11/5.
//  Copyright © 2018年 Carisok. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainRouter: MainWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        
        let stroyb = UIStoryboard.init(name: "Main", bundle: nil)
        let view = stroyb.instantiateViewController(withIdentifier: "MainViewController") as! MainViewController
        
        let viewcontrollers = [IndexRouter.createModule(),
                               ConversationListRouter.createModule(),
                               ReservationRouter.createModule(),
                               MeRouter.createModule()]
        
//        viewcontrollers.forEach {
//            $0.tabBarItem = UITabBarItem.init(title: "消息", image: nil, tag: 0)
//        }
        let interactor = MainInteractor()
        let router = MainRouter()
        let presenter = MainPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        view.viewControllers = viewcontrollers
        return view
    }
}
